base/urls.py
"""URL patterns for 'base' app."""

from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('latex', views.latex, name='latex'),
]

levanta-requisitos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

requisitos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

unwaste/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'))),
]

base/models.py
import re

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    name = models.CharField(max_length=64)
    email = models.EmailField(unique=True)
    is_business = models.BooleanField(default=False)
    cpf = models.CharField(null=True, blank=True, unique=True, max_length=14)
    cnpj = models.CharField(null=True, blank=True, unique=True, max_length=18)
    cpf_clean = models.BigIntegerField(null=True, blank=True, unique=True)
    cnpj_clean = models.BigIntegerField(null=True, blank=True, unique=True)

    def save(self, *args, **kwargs):
        # Temporary fix, make sure to address this later.
        self.username = self.email

        if self.cpf:
            self.cpf_clean = int(re.sub(r'\D', '', self.cpf))
        if self.cnpj:
            self.cnpj_clean = int(re.sub(r'\D', '', self.cnpj))
        super(User, self).save(*args, **kwargs)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, models.CASCADE, 'password_reset_requests')
    timestamp = models.DateTimeField()
    expiry = models.DateTimeField()
    token = models.CharField(max_length=36, unique=True)
    done = models.BooleanField(default=False)


class WasteCollectionRequest(models.Model):
    WASTE_TYPE_ABS = 'ABS'
    WASTE_TYPE_ALUMINUM = 'ALU'
    WASTE_TYPE_PET = 'PET'
    WASTE_TYPE_CHOICES = [
        (WASTE_TYPE_ABS, 'ABS Plastic (acrylonitrile butadiene styrene)'),
        (WASTE_TYPE_ALUMINUM, 'Aluminum'),
        (WASTE_TYPE_PET, 'PET Plastic (polyethylene terephthalate)'),
    ]
    STATUS_ACCEPTED = 'A'
    STATUS_PENDING = 'P'
    STATUS_REJECTED = 'R'
    STATUS_CHOICES = [
        (STATUS_ACCEPTED, 'Request accepted.'),
        (STATUS_PENDING, 'Request pending.'),
        (STATUS_REJECTED, 'Request rejected.'),
    ]

    user = models.ForeignKey(User, models.CASCADE, 'collection_requests')
    timestamp = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=2048)
    kilogram_amount = models.DecimalField(max_digits=5, decimal_places=2)
    desired_collection_date = models.DateField()
    waste_type = models.CharField(
        max_length=3,
        choices=WASTE_TYPE_CHOICES,
        default=WASTE_TYPE_ALUMINUM
    )
    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        default=STATUS_PENDING
    )

base/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from . import models


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'name',
            'email',
            'is_business',
            'cpf',
            'cnpj',
            'password1',
            'password2',
        )

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['cpf'].label = 'CPF'
        self.fields['cnpj'].label = 'CNPJ'

        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

    def clean(self):
        data = self.cleaned_data
        is_business = data.get('is_business')
        cpf = data.get('cpf')
        cnpj = data.get('cnpj')

        if is_business and not cnpj:
            self.add_error('cnpj', 'Please insert your CNPJ.')
        elif not is_business and not cpf:
            self.add_error('cpf', 'Please insert your CPF.')
        else:
            return data


class PasswordResetRequestForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super(PasswordResetRequestForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label


class DateInput(forms.DateInput):
    input_type = 'date'


class CollectionRequestForm(forms.ModelForm):
    class Meta:
        model = models.WasteCollectionRequest
        fields = (
            'address',
            'kilogram_amount',
            'waste_type',
            'desired_collection_date',
        )
        widgets = {'desired_collection_date': DateInput()}

base/views.py
"""Views for base app."""

import uuid
from datetime import datetime, timedelta

from django.conf import settings
from django.contrib.auth import login, logout
from django.contrib.auth.forms import SetPasswordForm
from django.core.mail import send_mail
from django.db import IntegrityError
from django.shortcuts import redirect, render
from django.urls import reverse

from . import forms, models, utils


def index(request):
    user = request.user
    collection_requests = None
    collection_request_form = forms.CollectionRequestForm(request.POST or None)

    if user.is_authenticated:
        collection_requests = (
            user.collection_requests.all().order_by('-timestamp'))

    if request.method == 'POST':
        if collection_request_form.is_valid() and user.is_business:
            r = collection_request_form.save(commit=False)
            r.user = user
            r.save()

        return redirect('base:index')

    context = {
        'collection_requests': collection_requests,
        'collection_request_form': collection_request_form,
    }

    return render(request, 'base/index.html', context)


def user_login(request):
    if request.user.is_authenticated:
        logout(request)

    form = forms.LoginForm(request, data=request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            next = request.GET.get('next', 'base:index')
            user = form.get_user()

            login(request, user)
            return redirect(next)

    context = {'page': 'login', 'form': form}

    return render(request, 'base/authentication.html', context)


def user_register(request):
    if request.user.is_authenticated:
        logout(request)

    form = forms.RegisterForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            try:
                user = form.save(commit=False)
                if not user.is_business:
                    if utils.check_cpf(user.cpf):
                        user.save()
                        login(request, user)
                        return redirect('base:index')

                    form.add_error('cpf', 'Invalid CPF number.')
            except IntegrityError:
                form.add_error(None, 'This user is already registered.')

    context = {'page': 'register', 'form': form}

    return render(request, 'base/authentication.html', context)


def password_reset(request):
    if request.user.is_authenticated:
        logout(request)

    form = forms.PasswordResetRequestForm(request.POST or None)

    if request.method == 'POST':
        try:
            user = models.User.objects.get(email=request.POST.get('email'))
            current_datetime = datetime.utcnow()

            pw_reset_request = models.PasswordResetRequest.objects.create(
                user=user,
                timestamp=current_datetime,
                expiry=current_datetime + timedelta(hours=1),
                token=uuid.uuid4()
            )

            message = request.build_absolute_uri(reverse(
                'base:password_reset_confirm',
                kwargs={'token': pw_reset_request.token}
            ))

            send_mail(
                'Reset your unWaste password',
                message,
                settings.DEFAULT_FROM_EMAIL,
                [user.email]
            )

            return redirect('base:password_reset_sent')
        except models.User.DoesNotExist:
            return redirect('base:password_reset_sent')

    context = {'page': 'reset', 'form': form}

    return render(request, 'base/password-reset.html', context)


def password_reset_sent(request):
    context = {'page': 'sent'}
    return render(request, 'base/password-reset.html', context)


def password_reset_confirm(request, token):
    pw_reset_request = models.PasswordResetRequest.objects.get(token=token)
    datetime_now = datetime.utcnow()

    if not pw_reset_request:
        return redirect('base:password_reset')

    if pw_reset_request.done:
        return redirect('base:password_reset')

    if pw_reset_request.expiry < datetime_now:
        return redirect('base:password_reset')

    user = pw_reset_request.user
    form = SetPasswordForm(user, request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            pw_reset_request.done = True
            pw_reset_request.save()

            return redirect('base:password_reset_done')

    context = {'page': 'confirm', 'form': form}

    return render(request, 'base/password-reset.html', context)


def password_reset_done(request):
    context = {'page': 'done'}
    return render(request, 'base/password-reset.html', context)


def user_logout(request):
    logout(request)
    return redirect('base:index')


def user_settings(request):
    return render(request, 'base/settings.html')


def about_us(request):
    return render(request, 'base/about-us.html')


def terms_of_service(request):
    return render(request, 'base/terms-of-service.html')


def privacy_policy(request):
    return render(request, 'base/privacy-policy.html')

base/templates/base/about-us.html
{% extends 'main.html' %}

{% block body %}
  <section>
    <h2>{% block title %}About us{% endblock %}</h2>
  </section>
{% endblock %}

base/templates/base/authentication.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
  {% if page == 'login' %}Login{% else %}Register{% endif %}
{% endblock %}

{% if page == 'register' %}
  {% block head %}
    <script src="{% static 'base/scripts/register.js' %}" defer></script>
  {% endblock %}
{% endif %}

{% block body %}
  <section>
    <div class="component margin-center">
      <h2>{% if page == 'login' %}Welcome back{% else %}Welcome{% endif %}</h2>
      <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="confirm" type="submit">
          {% if page == 'login' %}Login{% else %}Register{% endif %}
        </button>
      </form>
      <p>
        {% if page == 'login' %}
          Forgot your password? <a href="{% url 'base:password_reset' %}">Reset it here.</a>
          Don't have an account yet? <a href="{% url 'base:register' %}">Register here.</a>
        {% else %}
          Already have an account? <a href="{% url 'base:login' %}">Login here.</a>
        {% endif %}
      </p>
    </div>
  </section>
{% endblock %}

base/templates/base/index-juridical.html
<section>
  <h2>Request a collection:</h2>
  <div class="component">
    <form method="post">
      {% csrf_token %}
      {{ collection_request_form }}
      <button class="confirm" type="submit">Submit request</button>
    </form>
  </div>
</section>
{% if collection_requests %}
  <section>
    <h2>Your requests:</h2>
    {% for r in collection_requests %}
      <div class="component">
        <h3><b>{{ r.timestamp }}</b></h3>
        <hr />
        <p><b>Address:</b> {{ r.address }}</p>
        <p><b>Amount:</b> {{ r.kilogram_amount }}kg</p>
        <p><b>Desired collection date:</b> {{ r.desired_collection_date }}</p>
        <p><b>Waste type:</b> {{ r.get_waste_type_display }}</p>
        <p>
          <b>Status:</b>
          <span data-request-status="{{ r.status }}"
            >{{ r.get_status_display }}</span
          >
        </p>
      </div>
    {% endfor %}
  </section>
{% endif %}

base/templates/base/index-landing-page.html
<section>
  <h1>unWaste</h1>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, laudantium
    similique nam exercitationem nobis tenetur animi quis voluptates optio illum
    voluptatem corporis quo accusantium doloremque reprehenderit eos aperiam
    laboriosam dolorem!
  </p>
  <a href="{% url 'base:login' %}">Login</a>
</section>

base/templates/base/index-physical.html
<section>
  <h2>Welcome back, {{ request.user.name }}!</h2>
  <p>
    For now, unWaste is only available for juridical persons, but soon, we will
    have a new section to better serve you.
  </p>
</section>

base/templates/base/index.html
{% extends 'main.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h2>{% block title %}Levantamento{% endblock %}</h2>
  {% bootstrap_messages %}
  <form class="my-3" method="post">
    {% csrf_token %}
    {% bootstrap_field form.author %}
    <div class="mb-3">
      {% bootstrap_label form.reference.label %}
      <select class="form-select" id="id_reference" name="reference" required>
        <option value selected>---------</option>
        {% for r in references %}
          <option
            title="{{ r }}"
            value="{{ r.pk }}"
            {% if not r.is_available %}disabled{% endif %}
          >
            {{ r }}
          </option>
        {% endfor %}
      </select>
    </div>
    {% bootstrap_field form.name %}
    {% bootstrap_field form.category %}
    {% bootstrap_field form.priority %}
    {% bootstrap_field form.version %}
    {% bootstrap_field form.description %}
    {% bootstrap_button button_type="submit" content="Enviar" %}
  </form>
  <hr />
  <h2 class="mb-3">Requisitos já levantados:</h2>
  <div
    class="row row-cols-1 row-cols-md-2 g-4"
    data-masonry="{'percentPosition': true }"
  >
    {% for r in requirements %}
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">
              {{ r.type }} | <strong>{{ r.name }}</strong>
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ r.category }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">{{ r.priority }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">
              {{ r.date|date:'d/m/Y' }} (V{{ r.version }})
            </h6>
            <p class="card-text">{{ r.description }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <a class="d-block text-center mt-3" href="{% url 'latex' %}">LaTeX</a>
{% endblock %}

base/templates/base/latex.html
{% extends 'main.html' %}

{% block body %}
  <h2>{% block title %}LaTeX{% endblock %}</h2>
  <a class="d-block mb-3" href="{% url 'index' %}">Voltar</a>
  <pre><code>{{ string }}</code></pre>
{% endblock %}

base/templates/base/password-reset.html
{% extends 'main.html' %}
{% load static %}

{% block title %}Password reset{% endblock %}

{% block body %}
  <section>
    <div class="component margin-center">
      <h2>
        {% if page == "reset" %}
          Enter your e-mail
        {% elif page == "sent" %}
          Check your e-mail
        {% elif page == "confirm" %}
          Enter a new password
        {% elif page == "done" %}
          Password reset complete
        {% endif %}
      </h2>
      <p>
        {% if page == "reset" %}
          Please enter your email below, if there is an account belonging to it,
          the password reset instructions will be sent to it.
        {% elif page == "sent" %}
          We've emailed you instructions for setting your password, if an
          account exists with the email you entered. If you don't receive an
          email, please make sure you've entered the address you registered
          with, and check your spam folder.
        {% elif page == "confirm" %}
          Please enter a new password below.
        {% elif page == "done" %}
          Your new password has been set. You may go ahead and
          <a href="{% url 'base:login' %}">log in</a> now.
        {% endif %}
      </p>
      {% if page == "reset" or page == "confirm" %}
        <form method="post">
          {% csrf_token %}
          {{ form }}
          <button class="confirm width-full" type="submit">
            Reset my password
          </button>
        </form>
      {% endif %}
    </div>
  </section>
{% endblock %}

base/templates/base/privacy-policy.html
{% extends 'main.html' %}

{% block body %}
  <section>
    <h2>{% block title %}Privacy policy{% endblock %}</h2>
    <p>
        Your privacy is important to us. It is unWaste's policy to respect your
        privacy with respect to any information we may collect from you on the
        unWaste website, and any other websites we own and operate.
    </p>
    <p>
        We only ask for personal information when it is required for us to provide
        you a service. We do this by fair and lawful means, with your knowledge and
        consent. We also tell you why we are collecting it and how it will be used.
    </p>
    <p>
        We only retain collected information for as long as necessary to provide the
        requested service. When we store data, we protect it within commercially
        acceptable means to prevent loss and theft, as well as unauthorized access,
        disclosure, copying, use or modification. We do not share personally
        identifiable information publicly or with third parties, except when
        required by law.
    </p>
    <p>
        Our website may have links to external websites that are not operated by us.
        Please be aware that we have no control over the content and practices of
        those and cannot accept responsibility for their privacy policies.
    </p>
    <p>
        You are free to refuse our request for personal information, with the
        understanding that we may not be able to provide you with some of the
        services you require.
    </p>
    <p>
        Continued use of our websites will be deemed acceptance of our practices
        around privacy and personal information. If you have any questions about how
        we handle user data and personal information, please contact us.
    </p>
  </section>
{% endblock %}

base/templates/base/settings.html
{% extends 'main.html' %}

{% block title %}Settings{% endblock %}

{% block body %}
  <section>
    <h2>Settings</h2>
  </section>
{% endblock %}

base/templates/base/terms-of-service.html
{% extends 'main.html' %}

{% block body %}
  <section>
    <h2>{% block title %}Terms of service{% endblock %}</h2>
    <p>
      This service platform and its content are controlled and operated by unWaste
      itself. All rights reserved.
    </p>
    <p>
      These terms of use are intended to define the rules to be followed for the
      use of the website and its services, without prejudice to the application of
      current legislation.
    </p>
    <p>
      By creating and using an account on unWaste, you automatically agree to the
      terms of use, and you are fully responsible for any and all acts performed
      by you on unWaste or third-party services related to it. If you do not agree
      with any of the terms and conditions set out below, you must not use this
      platform. You also agree to the terms described in our privacy policy.
    </p>
    <p>
      If you would like to give us feedback about unWaste, have questions or need
      to address any matter related to these terms of use, please contact us.
    </p>
    <p>
      We reserve the right to suspend or cancel, at any time, your access to the
      application in case of suspicion of fraud, illegally obtaining a benefit or
      advantage, or for failing to comply with any conditions set forth in these
      terms of use, in the privacy policy or applicable law. In such cases, no
      compensation will be due to you, and unWaste will be able to take the
      competent action of recourse, if necessary, as well as take any other
      measures necessary to pursue and protect your interests.
    </p>
    <p>
      To access unWaste and use its services, it is necessary to register. To
      register, you will provide us with personal information such as date of
      birth, e-mail, CPF, cnpj of your company or where you work and full name. To
      learn more about personal data privacy at unWaste, visit our privacy policy.
    </p>
    <p>To use unWaste, you must be at least 18 years old.</p>
    <p>
      Upon registration, you will be the holder of an account that can only be
      accessed by authorized persons. If unWaste detects any account made from
      false information or access by unauthorized persons, that account will be
      automatically suspended and possibly deleted in the future.
    </p>
    <p>
      From now on, you undertake to keep your personal information up to date. You
      also agree that you will keep your login and password secure and out of
      reach of third parties, and you will not allow your account on the platform
      to be used by unauthorized persons. In this way, the user is responsible for
      all actions carried out on his account.
    </p>
    <p>
      All rights related to unWaste and its functionalities are the exclusive
      property of the team and its authors, including with regard to their texts,
      images, layouts, codes, databases, illustrations and other content produced
      directly or indirectly by the unWaste team. unWaste content is protected by
      copyright and intellectual property law. It is prohibited to use, copy,
      reproduce, modify, translate, publish, transmit, distribute, display,
      license, sell or exploit the unWaste content. Any unauthorized use of
      unWaste content will be considered copyright and intellectual property
      infringement.
    </p>
    <p>
      For the unWaste project team, the quality of the materials made available to
      the user is of paramount importance. Therefore, we reaffirm that unWaste
      guarantees that all rights, title and interest in the service provided by us
      will remain with unWaste.
    </p>
    <p>
      You are solely responsible for your use of unWaste and shall abide by the
      rules of these terms of use, as well as the law applicable to unWaste.
    </p>
    <p>
      unWaste and third parties will not be liable under any circumstances for
      direct or indirect damages that result from or are related to access, use or
      inability to access or use unWaste.
    </p>
  </section>
{% endblock %}